#!/bin/bash
wget https://apt.puppetlabs.com/puppetlabs-release-trusty.deb
sudo dpkg -i puppetlabs-release-trusty.deb
sudo apt-get update
sudo apt-get install puppet
sudo puppet resource package puppet ensure=latest
sudo puppet agent --disable 
sudo puppet module install puppetlabs-apt
